### PR TITLE
feat: Add TokenReference limit exceeded response code for TokenReject

### PR DESCRIPTION
**Pull request by MrValioBg**
**Description**:
Adds new status for TokenReject for the case where the transaction attempts to add more than allowed rejections/token references to the List.

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by iwsimon — COMMENTED** [review]
Please merge from the latest main branch. This code 349 has been taken.

**Comment by jsync-swirlds** [comment]
> Please merge from the latest main branch. This code 349 has been taken.

The _destination branch_, `hip-904-proto-updates`, is out of date with respect to `main`, which is why github doesn't see an error.

**Comment by MrValioBg** [comment]
> > Please merge from the latest main branch. This code 349 has been taken.
> 
> The _destination branch_, `hip-904-proto-updates`, is out of date with respect to `main`, which is why github doesn't see an error.

Yes indeed. @jsync-swirlds @iwsimon. 
If possible could someone update it directly as I don't have a permission for that 🙂  🙏🏻

**Comment by jsync-swirlds** [comment]
> > > Please merge from the latest main branch. This code 349 has been taken.
> > 
> > 
> > The _destination branch_, `hip-904-proto-updates`, is out of date with respect to `main`, which is why github doesn't see an error.
> 
> Yes indeed. @jsync-swirlds @iwsimon. If possible could someone update the hip-904-proto-updates directly as I don't have a permission for that 🙂 🙏🏻

Done, but it appears that made this PR a bit wonky...

**Review by jsync-swirlds — APPROVED** [review]

**Pull request closed without merging**
