### PR TITLE
Refactor adjust message to match approval (HIP 336)

### PR DESCRIPTION
**Pull request by superboo**
Signed-off-by: Albert Tam <albert.tam@hedera.com>

**Description**:
Refactor CryptoAdjustAllowanceTransactionBody to have a similar structure to CryptoApproveAllowanceTransactionBody. This change avoids the question of why do adjust + approval have different structures yet have very similar behaviors. It also removes the need to make tokenId optional in the case of hbar approvals.

Added MULTIPLE_SPENDER_APPROVALS ResponseCodeEnum value.

Changes made as outlined in HIP 336.

**Related issue(s)**:

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by tinker-michaelj — APPROVED** [review]
LGTM

**Review by steven-sheehy — APPROVED** [review]
I have a discussion item about maybe needing a list of final allowances in the record, but that can be a separate issue.

**Review by tinker-michaelj — DISMISSED** [review]
LGTM

**Review by SimiHunjan — DISMISSED** [review]

**Review by steven-sheehy — APPROVED** [review]

**Comment by superboo** [comment]
Not needed, superseded by https://github.com/hashgraph/hedera-protobufs/pull/151

**Pull request closed without merging**
